##
# This file is part of the IVMS Online.
#
# @copyright 2023 © by Rafał Wrzeszcz - Wrzasq.pl.
##

AWSTemplateFormatVersion: "2010-09-09"

Transform:
    - "WrzasqPlCformMacro"

Parameters:
    ProjectKey:
        Type: "String"

    ProjectVersion:
        Type: "String"

    ComponentId:
        Type: "String"

Resources:
    InventoryTable:
        Type: "AWS::DynamoDB::Table"
        DeletionPolicy: "Retain"
        Properties:
            KeySchema:
                -
                    AttributeName: "customerAndVesselId"
                    KeyType: "HASH"
                -
                    AttributeName: "inventoryKey"
                    KeyType: "RANGE"
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: true
            StreamSpecification:
                StreamViewType: "NEW_AND_OLD_IMAGES"
            BillingMode: "PAY_PER_REQUEST"

Outputs:
    InventoryTableName:
        Value: !Ref "InventoryTable"

    InventoryTableArn:
        Value: !GetAtt "InventoryTable.Arn"

    InventoryStreamArn:
        Value: !GetAtt "InventoryTable.StreamArn"
        Export:
            Name: !Sub "${ProjectKey}:${ProjectVersion}:${ComponentId}:InventoryStream:Arn"
